packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@aws-sdk/client-scheduler": ^3.540.0
  "@babel/core": ^7.24.0
  "@babel/preset-env": ^7.24.0
  "@babel/preset-typescript": ^7.24.6
  "@babel/runtime": ^7.24.0
  "@clerk/clerk-expo": ^1.1.4
  "@expo/metro-config": ^0.18.3
  "@ianvs/prettier-plugin-sort-imports": ^4.2.1
  "@jest/globals": ^29.7.0
  "@neondatabase/serverless": ^0.9.0
  "@next/eslint-plugin-next": ^14.1.4
  "@react-native-async-storage/async-storage": 1.23.1
  "@react-native-community/datetimepicker": 8.0.1
  "@react-native-picker/picker": 2.7.5
  "@react-navigation/drawer": ^6.6.11
  "@rehookify/datepicker": ^6.6.1
  "@serverless/typescript": ^3.38.0
  "@shopify/flash-list": 1.6.4
  "@tamagui/babel-plugin": ^1.100.0
  "@tamagui/config": ^1.100.0
  "@tamagui/lucide-icons": ^1.100.0
  "@tamagui/toast": ^1.100.0
  "@tanstack/react-query": ^5.25.0
  "@testcontainers/postgresql": ^10.9.0
  "@testing-library/react-native": ^12.5.1
  "@trpc/client": 11.0.0-rc.330
  "@trpc/react-query": 11.0.0-rc.330
  "@trpc/server": 11.0.0-rc.330
  "@turbo/gen": ^1.13.2
  "@types/aws-lambda": ^8.10.136
  "@types/eslint": ^8.56.7
  "@types/node": ^20.13.0
  "@types/pg": ^8.11.2
  "@types/react-datepicker": ^6.2.0
  "@typescript-eslint/eslint-plugin": ^7.5.0
  "@typescript-eslint/parser": ^7.5.0
  autoprefixer: ^10.4.19
  axios: ^1.6.8
  burnt: ^0.12.2
  cheerio: 1.0.0-rc.12
  date-fns: ^3.6.0
  date-fns-tz: ^3.1.3
  dotenv-cli: ^7.4.1
  drizzle-kit: ^0.22.1
  drizzle-orm: ^0.31.0
  drizzle-zod: ^0.5.1
  eslint: ^8.57.0
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^1.13.2
  eslint-plugin-import: ^2.29.1
  eslint-plugin-jsx-a11y: ^6.8.0
  eslint-plugin-react: ^7.34.1
  eslint-plugin-react-hooks: ^4.6.0
  expo: ~51.0.11
  expo-constants: ~16.0.2
  expo-font: ^12.0.7
  expo-linear-gradient: ~13.0.2
  expo-linking: ~6.3.1
  expo-router: ~3.5.15
  expo-secure-store: ^13.0.1
  expo-server-sdk: ^3.9.0
  expo-splash-screen: ~0.27.5
  expo-status-bar: ~1.12.1
  jest: ^29.7.0
  jest-expo: ^50.0.4
  pg: ^8.11.3
  pino: ^8.20.0
  pino-pretty: ^11.0.0
  postcss: ^8.4.38
  postgres: ^3.4.4
  prettier: ^3.2.5
  prettier-plugin-tailwindcss: ^0.5.13
  react-datepicker: ^6.9.0
  react-native: ~0.74.2
  react-native-css-interop: ~0.0.34
  react-native-gesture-handler: ~2.16.2
  react-native-reanimated: ~3.10.1
  react-native-safe-area-context: ~4.10.1
  react-native-screens: ~3.31.1
  react-native-svg: ^15.1.0
  serverless-esbuild: ^1.52.1
  serverless-offline: ^13.3.3
  superjson: 2.2.1
  tailwindcss: ^3.4.3
  tailwindcss-animate: ^1.0.7
  tamagui: ^1.100.0
  testcontainers: ^10.9.0
  ts-jest: ^29.1.4
  ts-node: ^10.9.2
  turbo: ^1.13.2
  typescript: ^5.5.3
  vite-tsconfig-paths: ^4.3.2
  vitest: ^1.4.0
  zod: ^3.22.4
  zustand: ^4.5.2

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
