[build]
  functions = "../backend/functions"
  command = "npx expo export -p web"
  publish = "apps/zotmeal/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
