import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import Toolbar from "@/components/ui/toolbar";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <Toolbar></Toolbar>
      <body>
        {children}
      </body>
    </html>
  );
}
