import type { MenuWithRelations } from "@zotmeal/db/src/schema";

// TODO: Replace with real data
export const brandywineData = {
  date: "1/22/2022",
  id: "123",
  price: "10.00",
  createdAt: "2022-01-22T00:00:00.000Z",
  updatedAt: "2022-01-22T00:00:00.000Z",
  restaurantId: "3314",
  start: "7:15",
  end: "11:00",
  period: "breakfast",
  stations: [
    {
      id: "111",
      name: "Honeycakes/Bakery",
      createdAt: "2022-01-22T00:00:00.000Z",
      updatedAt: "2022-01-22T00:00:00.000Z",
      restaurantId: "3314",
      dishes: [
        {
          name: "Blueberry Scone",
          id: "123",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "A delicious blueberry scone",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Breakfast Muffin",
          id: "312",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "A delicious breakfast muffin",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 1",
          id: "444",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "A delicious side dish",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 2",
          id: "555",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "A delicious side dish 2",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
      ],
    },
    {
      id: "222",
      name: "Hearth/Pizza",
      createdAt: "2022-01-22T00:00:00.000Z",
      updatedAt: "2022-01-22T00:00:00.000Z",
      restaurantId: "3314",
      dishes: [
        {
          name: "Blueberry Scone",
          id: "123",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Breakfast Muffin",
          id: "312",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 1",
          id: "444",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 2",
          id: "555",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
      ],
    },
    {
      id: "222",
      name: "Hearth/Pizza 2",
      createdAt: "2022-01-22T00:00:00.000Z",
      updatedAt: "2022-01-22T00:00:00.000Z",
      restaurantId: "3314",
      dishes: [
        {
          name: "Blueberry Scone",
          id: "123",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Breakfast Muffin",
          id: "312",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 1",
          id: "444",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 2",
          id: "555",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
      ],
    },
    {
      id: "222",
      name: "Hearth/Pizza 3",
      createdAt: "2022-01-22T00:00:00.000Z",
      updatedAt: "2022-01-22T00:00:00.000Z",
      restaurantId: "3314",
      dishes: [
        {
          name: "Blueberry Scone",
          id: "123",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Breakfast Muffin",
          id: "312",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 1",
          id: "444",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 2",
          id: "555",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
      ],
    },
  ],
} satisfies MenuWithRelations;

// TODO: Replace with real data
export const anteateryData = {
  date: "1/22/2022",
  id: "5555",
  price: "10.00",
  createdAt: "2022-01-22T00:00:00.000Z",
  updatedAt: "2022-01-22T00:00:00.000Z",
  restaurantId: "3056",
  start: "7:15",
  end: "11:00",
  period: "breakfast",
  stations: [
    {
      id: "111",
      name: "Honeycakes/Bakery",
      createdAt: "2022-01-22T00:00:00.000Z",
      updatedAt: "2022-01-22T00:00:00.000Z",
      restaurantId: "3056",
      dishes: [
        {
          name: "Blueberry Scone",
          id: "123",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Breakfast Muffin",
          id: "312",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 1",
          id: "444",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 2",
          id: "555",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
      ],
    },
    {
      id: "222",
      name: "Hearth/Pizza",
      createdAt: "2022-01-22T00:00:00.000Z",
      updatedAt: "2022-01-22T00:00:00.000Z",
      restaurantId: "3056",
      dishes: [
        {
          name: "Pizza",
          id: "9122",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Breakfast Muffin",
          id: "312",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Bakery",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 1",
          id: "444",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
        {
          name: "Side 2",
          id: "555",
          createdAt: "2022-01-22T00:00:00.000Z",
          updatedAt: "2022-01-22T00:00:00.000Z",
          category: "Sides",
          description: "Item Description",
          dietRestriction: {
            dishId: "123",
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            containsEggs: false,
            containsFish: false,
            containsPeanuts: false,
            containsMilk: false,
            containsShellfish: false,
            containsSesame: false,
            containsSoy: false,
            containsTreeNuts: false,
            containsWheat: false,
            isGlutenFree: false,
            isHalal: false,
            isKosher: false,
            isLocallyGrown: false,
            isOrganic: false,
            isVegan: false,
            isVegetarian: false,
          },
          nutritionInfo: {
            createdAt: "2022-01-22T00:00:00.000Z",
            updatedAt: "2022-01-22T00:00:00.000Z",
            dishId: "123",
            servingSize: "1",
            calories: "300",
            dietaryFiberG: "2g",
            proteinG: "10g",
            sugarsMg: "5g",
            totalCarbsG: "30g",
            totalFatG: "15g",
            transFatG: "0g",
            saturatedFatG: "5g",
            sodiumMg: "300mg",
            cholesterolMg: "50mg",
            vitaminAIU: "10%",
            vitaminCIU: "10%",
            calciumMg: "10%",
            ironMg: "10%",
            servingUnit: "g",
            caloriesFromFat: "2",
          },
        },
      ],
    },
  ],
} satisfies MenuWithRelations;
